# Generated by Django 5.2.10 on 2026-01-24 18:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField()),
            ],
            options={
                'db_table': 'tags',
                'indexes': [models.Index(fields=['name'], name='tags_name_38920e_idx'), models.Index(fields=['category'], name='tags_categor_73c8b8_idx')],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
