# Generated by Django 5.2.10 on 2026-01-24 18:19

import django.db.models.deletion
import media_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=media_app.models.upload_to_user_folder)),
                ('file_size', models.BigIntegerField()),
                ('media_type', models.IntegerField(choices=[(1, 'Image'), (2, 'Video')])),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.media')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'db_table': 'media_tags',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(related_name='media', through='media_app.MediaTag', to='tags.tag'),
        ),
        migrations.AddIndex(
            model_name='mediatag',
            index=models.Index(fields=['media'], name='media_tags_media_i_b1abae_idx'),
        ),
        migrations.AddIndex(
            model_name='mediatag',
            index=models.Index(fields=['tag'], name='media_tags_tag_id_38404b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediatag',
            unique_together={('media', 'tag')},
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['user', 'uploaded_at'], name='media_user_id_9f1794_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type'], name='media_media_t_9a1c04_idx'),
        ),
    ]
