# Generated by Django 5.2.10 on 2026-01-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
        ('tags', '0002_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='ai_classifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='media', through='media_app.MediaTag', to='tags.tag'),
        ),
    ]
