# Generated by Django 5.2.10 on 2026-01-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_media_ai_classifications_alter_media_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='tags',
        ),
        migrations.DeleteModel(
            name='MediaTag',
        ),
    ]
