services:
  imaginarium:
    container_name: imaginarium
    build:
      context: ../src/django/imaginarium/
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - ai-classification
    env_file:
      - env/imaginarium.env
    volumes:
      - media_data:/code/media
      - thumbnails_data:/code/thumbnails
    ports:
      - "8000:8000"

  imaginarium-front:
    container_name: imaginarium-front
    build:
      context: ../src/angular/imaginarium-front/
    restart: unless-stopped
    depends_on:
      - imaginarium
    ports:
      - "8080:80"

  postgres:
    container_name: imaginarium-postgres
    image: postgres:14.2
    restart: unless-stopped
    env_file:
      - env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: imaginarium-redis
    image: redis
    restart: unless-stopped

  ai-classification:
    container_name: imaginarium-ai
    build:
      context: ../src/fastapi/ai-classification/
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8001:8000"

  nginx:
    container_name: imaginarium-nginx
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - "4444:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_data:/var/www/media:ro
      - thumbnails_data:/var/www/thumbnails:ro
    depends_on:
      - imaginarium
      - imaginarium-front
      - postgres
      - redis
      - ai-classification

volumes:
  postgres_data:
  media_data:
  thumbnails_data: