# Generated by Django 5.2.10 on 2026-01-24 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='media_app.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='AlbumMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_medias', to='albums.album')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_medias', to='media_app.media')),
            ],
            options={
                'db_table': 'album_media',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='media',
            field=models.ManyToManyField(related_name='albums', through='albums.AlbumMedia', to='media_app.media'),
        ),
        migrations.AddIndex(
            model_name='albummedia',
            index=models.Index(fields=['album', 'order'], name='album_media_album_i_af34b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='albummedia',
            unique_together={('album', 'media')},
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['user', 'created_at'], name='albums_user_id_77264a_idx'),
        ),
    ]
