# Generated by Django 5.2.10 on 2026-01-24 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('groups', '0001_initial'),
        ('media_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(max_length=64, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission_level', models.IntegerField(choices=[(1, 'View'), (2, 'Download'), (3, 'Edit')], default=1)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_app.media')),
                ('shared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shares',
                'indexes': [models.Index(fields=['share_token'], name='shares_share_t_a74344_idx'), models.Index(fields=['shared_by_user'], name='shares_shared__c193be_idx'), models.Index(fields=['shared_with_user'], name='shares_shared__6d2b86_idx'), models.Index(fields=['shared_with_group'], name='shares_shared__34bac4_idx')],
            },
        ),
    ]
